[package]
name = "http-remote"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.6"
qr2term = "0.3.3"
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.48.0", features = ["full"] }
toml = "0.9.10"
uuid = { version = "1.18.1", features = ["v4"] }
